
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnxnbouzvwhgdjcwwupf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ueG5ib3V6dndoZ2RqY3d3dXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDczNjYsImV4cCI6MjA2NTYyMzM2Nn0.Kv19J4Lv263XtrxBlqXoRpYq_z12XVvSwC4zb0GgJbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
