// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rktjpemsxgjokyvzaspb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrdGpwZW1zeGdqb2t5dnphc3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzY0ODcsImV4cCI6MjA2NDAxMjQ4N30.pXVTWg-hzSjYtEi_Gyt1o8rWRgUAKb2WypDoySVpIus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);